### ISSUE TITLE
Different results from command-line vs JS Object usage

### ISSUE THREAD

**Issue by a-nwhitmont** [yahoo/blink-diff#16]
During testing of blink-diff I have experienced different results from the command-line usage vs. the Javascript Object usage. 

### Images used for this test:

people.png
![people](https://cloud.githubusercontent.com/assets/11202280/6537720/8f9b84ec-c40e-11e4-9fa5-43cd726eb2b3.png)

people2.png
![people2](https://cloud.githubusercontent.com/assets/11202280/6537726/9757d5b4-c40e-11e4-8343-e467a256fd3b.png)

## Command-line Usage

Command-line script:
       `./node_modules/blink-diff/bin/blink-diff --output blinkdiff-people.png people.png people2.png`

Command-line result:
```
bash-3.2$ ./blinkcli.sh
Blink-Diff 1.0.7
Copyright (C) 2014 Yahoo! Inc.
Images are visibly different
16297 pixels are different
Wrote differences to blinkdiff-people.png
Time: 197ms
Differences: 16297 (6.52%)
FAIL
```

Output file: blinkdiff-people.png - (Works as expected)
![blinkdiff-people](https://cloud.githubusercontent.com/assets/11202280/6537790/389fa366-c40f-11e4-82ed-73eb1a51f9db.png)

## Javascript Object Usage

blink.js
``` javascript
#!/usr/bin/env node

BlinkDiff = require('blink-diff')

var diff = new BlinkDiff({
    imageAPath: 'people.png',
    imageBPath: 'people2.png',

    imageOutputPath: 'blink-diff-people.png',

    verbose: true
});


diff.run(function (error) {
    console.log(error ? 'Failed' + error : 'Passed');
});
```

Run the script:
`bash-3.2$ node blink.js`

Output results (NOT as expected)
```
bash-3.2$ node blink.js 
Passed
```

## Summary
Why are the results different?  The results from the command-line usage are as expected, while the JS Object usage says "Passed" when it should say "Fail" and produce the output image.

**Comment by marcelerz** [comment]
Thank you for the well composed bug-report!

This was an error in the documentation. The first parameter is the typical Node error object for callbacks (when there was an error - not a difference). The second parameter, however, holds detailed information about the comparison - including the result. I updated the documentation and now the results are consistent. The code should look something like this:

```javascript
#!/usr/bin/env node

BlinkDiff = require('blink-diff');

var diff = new BlinkDiff({
    imageAPath: 'people.png',
    imageBPath: 'people2.png',

    imageOutputPath: 'blink-diff-people.png',

    verbose: true
});

diff.run(function (error, result) {
    console.log(diff.hasPassed(result.code) ? 'Passed' : 'Failed with ' + result.differences + ' differences - ' + error);
});
```

The result is:
![blink-diff-people](https://cloud.githubusercontent.com/assets/1312730/6538864/c619b7c4-c41c-11e4-8652-2d244511bf81.png)

Thanks! :+1:
