### ISSUE TITLE
'blink-diff' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by stplajeet** [yahoo/blink-diff#26]
Once I am running the below command

blink-diff --output image.png images/image1.png images/image2.png

it is flashing me an error on my console - 
'blink-diff' is not recognized as an internal or external command, operable program or batch file.

Can anyone suggest what might the issue

**Comment by marcelerz** [comment]
Have you installed ```blink-diff``` globally?

You can do that with 
```
npm install -g blink-diff
```
After that, you can access ```blink-diff``` directly from the command line. 

```
blink-diff --output image.png images/image1.png images/image2.png
```

If you've installed it locally via ```npm install blink-diff``` (without the ```-g```), then you can only access it with a relative path from where you've installed it:

```
./node_modules/blink-diff/bin/blink-diff --output image.png images/image1.png images/image2.png
```
