### ISSUE TITLE
Can't have a delta equal to zero

### ISSUE THREAD

**Issue by Jeanreptile** [yahoo/blink-diff#28]
Hello,

I want to compare my images with a delta of zero. But if I put a zero value to delta it will be overridden here:
`this._delta = options.delta || 20;`

I saw that there is the same thing for threshold.
If I override the delta to zero manually in the source code, I have the diff image that I need.

I can make a PR to check if `options.delta` and `options.threshold `are undefined.
But is there a legitimate reason that delta and threshold can't be equal to zero?

Thanks,

**Comment by marcelerz** [comment]
Now, there is no particular reason for that. For the time being, you could use a very small number to get around that. Something like "0.0001".

**Comment by Jeanreptile** [comment]
I tried to use "0.0001" but even with a very small number, when it's not zero I don't what what I expect:

image A:
![image_a](https://cloud.githubusercontent.com/assets/8156620/16739529/e2529980-479a-11e6-9255-12a89ed6125b.png)

image B:
![image_b](https://cloud.githubusercontent.com/assets/8156620/16739526/e251b556-479a-11e6-954c-e8a17af4cc30.png)

Diff image with zero delta:
![diff_image_with_zero_delta](https://cloud.githubusercontent.com/assets/8156620/16739527/e25231ca-479a-11e6-88c7-44fa387064e2.png)

Diff image with delta value at 1 or 0.0001 or even 0.000001
![diff_image_with_not_zero_delta](https://cloud.githubusercontent.com/assets/8156620/16739528/e2529034-479a-11e6-8ee6-46a0160eb4f4.png)

**Comment by marcelerz** [comment]
This should be fixed with 1.0.13.
